# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7239db98bc61f48f388cb6658efd3cfef25ef6ce507f5bd342cbfe0ae4eab6dc04588711f7943e9deb5ac0a470a8f6a39c975c6082433f7283bc109ca829045

test:
  secret_key_base: 5edf67f662350fdd28f1ac7008cd91a60fc6762b09b8578476111285a10583b9661ddcf701341bd883d6ab6e76004b5a5dc52b754bfdd1d7470b3a5f96bd52a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
